# Site settings
email: kcrong@kim82536.pe.kr
baseurl: "/blog"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: HERE
description: essay
url: "https://kcrong.github.io"
twitter_username:
default_img:

# Profile settings
name: kcrong
profile_img: https://avatars2.githubusercontent.com/u/13450715?v=3&s=460
profile: what < how < whom
social:
  github: https://github.com/kcrong

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
